### ISSUE TITLE
Installing fails because of path issues

### ISSUE THREAD

**Issue by alexandrubisa** [ctaylo21/jarvis#17]
On a fresh mac install, there are several things that fail because of pathing issues. I don't know enough bash to fix all of them

1) Backup.sh creates a files array 
`files=("$HOME/.config/nvim" "$HOME/.zshrc" "$HOME/.tmux.conf")` 

However, if the nvim config is missing (due to nvim not installed), the script will stop after attempting to backup that file, and zshrc backup is not done. The else block is also not called for some reason. 

2) Link.sh does not get the current directory and as a result does not link anything. 
`$INSTALLDIR` is defined in install.sh, but not passed over to link.sh for some reason

3) The copy command for the space theme for vim-airline is not correct. Current command is 
`cp ./config/nvim/space.vim ./config/nvim/plugged/vim-airline-themes/autoload/airline/themes/space.vim` 
and should be something like:
`cp ./config/nvim/space.vim $HOME/.config/nvim/plugged/vim-airline-themes/autoload/airline/themes/space.vim`

**Comment by ctaylo21** [comment]
Thanks for the issue! I don't doubt that there are a decent amount of bugs in the install script. I've only used it a hand full of times, and when I add things to it I don't blow away my whole build to test it. 

Having said that, I'll make these fixes and any others you find. As always, a PR is welcome for some of the simpler things (like incorrect paths). Thanks again!

**Comment by ctaylo21** [comment]
I've decided to essentially make the `install.sh` script deprecated. It's very difficult to maintain and the work required to make sure it worked across all use cases isn't worth it to me given that it's only done on a fresh install. I've updated the docs to show that the script is unsupported, but I left it because it can be used as a guide to getting most of the required dependencies set up.
