### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by eflo11** [ctaylo21/jarvis#2]
Ran into issues with install after commenting out mv of previous error. 
![image](https://user-images.githubusercontent.com/6474512/35938082-fa2744e8-0bfc-11e8-82a3-8d61c4be3066.png)

**Comment by alex-shamshurin** [comment]
I run into the same error. How to fix it? So why it's closed?

**Comment by ctaylo21** [comment]
I believe it's closed because it was fixed in this [commit]https://github.com/ctaylo21/jarvis/commit/6f6feaf6505c9b24a98eca27e4543ff3d9609ce5l). Some of the functions/variables are not available until you run `:PlugInstall`.

Also, that install script has been deprecated. I left it as a guide for installing everything, but with a big disclaimer that it no longer works and won't be maintained due to the difficulty in keeping it up to date.

**Comment by ctaylo21** [comment]
Was your error the exact same lines? I might need to do more try/catch wrapping in the init.vim.
