### ISSUE TITLE
colorls dependency

### ISSUE THREAD

**Issue by canibanoglu** [ctaylo21/jarvis#30]
Hello,

I've shamelessly ripped off jarvis and have been modifiying a bit for myself and one thing I've noticed that there is a dependency on `colorls` that doesn't appear in the installation scripts. The result is you can't use `ls` after setup until you install colorls.

I'm happy to send in a PR to do `gem install colorls` :)

**Comment by ctaylo21** [comment]
Ah good catch! I recently "deprecated" the install script in a sense because it's painful to maintain it very rarely gets used. But I'm happy to update the docs to include the `colorls` installation command as a manual step. If you want to do a PR, that would be great! If not, I'll add it sometime this week. Thanks again!
