### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by canibanoglu** [ctaylo21/jarvis#31]
As I mentioned in #30, I've been busy ripping this off and one of my requirements was to get my version to run on Linux (more specifically Ubuntu under WSL2) to work. 

I have checked out previous issues and I can see that there have been some requests for a linux version of this and that you've made some suggestions and that you only run this when you have a new computer.

The good news is that "porting" this to work with linux is a lot less work that I would have expected thanks to [linuxbrew](linuxbrew.sh)! I have got this (well, a modified version of this) to work just fine with the `brew install ...` commands. 

Another idea that I had while porting was to use `asdf` to manage the languages. I see that `node` and `python` are installed by brew but honestly I believe that most of us are using many version managing scripts like 'nvm', 'rvm' and this only adds to the complication. I've recently switched to `asdf` for managing different language versions and also integrated `asdf` to be used during the installation. 

Related to this and #30, 'ruby' is a dependency of JARVIS and should be included in the install script. Then again OS X does ship with `ruby` installed.

**Comment by ctaylo21** [comment]
Hi, thanks for the issue! The installation script is a tough one, because as you mentioned, I used it only when I get a new computer. To keep it updated as Jarvis evolves, I would likely spend a decent amount of time debugging and testing it.  I only recently discovered it was broken, and probably has been for a while as one of the commands stopped working.

I marked the install script as "deprecated", but I left it in the repo as a reference for getting the project set up because it still contains most of the steps needed. 

Regarding multiple language versions, I do think that is a valid issue. That is another reason to not have the install script unless I was going to spend a lot of time making it cross-platform and take all of those issues into consideration. That felt like a pretty big effort given that I won't use it, so I will probably leave that as something that I would gladly take PR's for, but probably won't support myself. Especially given that I don't use Linux right now. 

I appreciate the issue, and I hope you are getting some good use out of the setup!
