### ISSUE TITLE
Denite is not setup with ripgrep to find hidden files. 

### ISSUE THREAD

**Issue by casperstorm** [ctaylo21/jarvis#36]
I found your config a few days back and love it, so thanks for that ❤️ 
However, you are missing the `--hidden` flag in the `file/rec` config in order to search for hidden files:

```
call denite#custom#var('file/rec', 'command', ['rg', '--files', '--glob', '!.git', '--hidden'])
```

**Comment by ctaylo21** [comment]
Thanks for the issue! This is a tougher one. I believe I left it out on purpose because I was consistently getting hidden files in my search when I was trying to look at my app's sources files. I typically don't edit my hidden files a lot, so I tend to want them excluded from fuzzy finding features to reduce clutter.

This one might be more of a personal preference that I'll leave up to others to add if they want it.

**Comment by casperstorm** [comment]
I see, that I understand. This is one of the reasons why I (very recently) switched to Vim. The customization. What works for you, does not necessarily work for me. Your setup was just a perfect starting point for me!

**Comment by ctaylo21** [comment]
Totally agree! Closing this, but anyone else with the same request will hopefully see this and know how to fix it. Thanks again!
